export const  GET_WRITTER_DATA_REQUEST = "GET_WRITTER_DATA_REQUEST";
export const  GET_WRITTER_DATA_FAILURE = "GET_WRITTER_DATA_FAILURE";
export const  GET_WRITTER_DATA_SUCCESS = "GET_WRITTER_DATA_SUCCESS";

export const  DELETE_WRITTER_DATA_REQUEST = "DELETE_WRITTER_DATA_REQUEST";
export const  DELETE_WRITTER_DATA_FAILURE = "DELETE_WRITTER_DATA_FAILURE";
export const  DELETE_WRITTER_DATA_SUCCESS = "DELETE_WRITTER_DATA_SUCCESS";

export const  POST_WRITTER_DATA_REQUEST = "POST_WRITTER_DATA_REQUEST";
export const  POST_WRITTER_DATA_FAILURE = "POST_WRITTER_DATA_FAILURE";
export const  POST_WRITTER_DATA_SUCCESS = "POST_WRITTER_DATA_SUCCESS";

export const  EDIT_WRITTER_DATA_REQUEST = "EDIT_WRITTER_DATA_REQUEST";
export const  EDIT_WRITTER_DATA_FAILURE = "EDIT_WRITTER_DATA_FAILURE";
export const  EDIT_WRITTER_DATA_SUCCESS = "EDIT_WRITTER_DATA_SUCCESS";